### ISSUE TITLE
Is there any way to change the API key on the go instead of relying on settings.py ?

### ISSUE THREAD

**Issue by Couaque** [paaksing/django-cassiopeia#4]
Hello, I am trying to change my API key on the go, and it is unfortunately not possible given that Django settings are not made to be changed during runtime anyway.

I was trying to access cass.riotapi.set_api_key like it is mentioned on the official documentation (first example), but it appears that there is no way to change it on the go.

Do you know what would be needed to add this feature to the library ?

Kind Regards,
Téo

**Comment by paaksing** [comment]
Hi there @Couaque , can you give me an example of why and what do you need to change at run time ? so I can get a better context

**Comment by paaksing** [comment]
@Couaque Sorry that I skim over the question `cass.set_riot_api_key` should work.

**Comment by paaksing** [comment]
Closing after 1 week of innactivity

**Comment by Couaque** [comment]
Hello, sorry for the late reply.
The response you gave me works, thanks a lot !
